# Generated by Django 5.0.6 on 2026-07-17 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0002_seed_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentproduct',
            name='category',
            field=models.CharField(choices=[('property', 'Property Investments'), ('forex', 'Forex Trading Accounts'), ('portfolio', 'Portfolio Management'), ('wealth', 'Wealth Building'), ('advisory', 'Investment Advisory'), ('business_funding', 'Business Funding Solutions'), ('future', 'Future Investment Opportunities')], max_length=32),
        ),
    ]
